// Loga klubů z thesportsdb.com — volně dostupné CDN pro fotbalová loga
export const CLUBS = [
  {
    slug: 'slavia-praha',
    name: 'SK Slavia Praha',
    short: 'Slavia',
    city: 'Praha',
    color: '#CC0000',
    bg: '#fff0f0',
    logo: '/logos/slavia-praha.png',
    keywords: ['Slavia', 'SK Slavia', 'Slavia Praha'],
  },
  {
    slug: 'sparta-praha',
    name: 'AC Sparta Praha',
    short: 'Sparta',
    city: 'Praha',
    color: '#AC1A2F',
    bg: '#fff0f2',
    logo: '/logos/sparta-praha.png',
    keywords: ['Sparta', 'AC Sparta', 'Sparta Praha'],
  },
  {
    slug: 'viktoria-plzen',
    name: 'FC Viktoria Plzeň',
    short: 'Plzeň',
    city: 'Plzeň',
    color: '#003087',
    bg: '#f0f4ff',
    logo: '/logos/viktoria-plzen.png',
    keywords: ['Plzeň', 'Viktoria Plzeň', 'Viktoria Plzen'],
  },
  {
    slug: 'banik-ostrava',
    name: 'FC Baník Ostrava',
    short: 'Baník',
    city: 'Ostrava',
    color: '#005CA9',
    bg: '#f0f6ff',
    logo: '/logos/banik-ostrava.png',
    keywords: ['Baník', 'Baník Ostrava', 'Banik Ostrava'],
  },
  {
    slug: 'sigma-olomouc',
    name: 'SK Sigma Olomouc',
    short: 'Sigma',
    city: 'Olomouc',
    color: '#003366',
    bg: '#f0f4ff',
    logo: '/logos/sigma-olomouc.png',
    keywords: ['Sigma', 'Sigma Olomouc', 'SK Sigma'],
  },
  {
    slug: 'bohemians-1905',
    name: 'Bohemians Praha 1905',
    short: 'Bohemians',
    city: 'Praha',
    color: '#007A33',
    bg: '#f0fff4',
    logo: '/logos/bohemians-1905.png',
    keywords: ['Bohemians', 'Bohemians 1905', 'Bohemka'],
  },
  {
    slug: 'slovan-liberec',
    name: 'FC Slovan Liberec',
    short: 'Liberec',
    city: 'Liberec',
    color: '#003DA5',
    bg: '#f0f4ff',
    logo: '/logos/slovan-liberec.png',
    keywords: ['Liberec', 'Slovan Liberec', 'FC Liberec'],
  },
  {
    slug: 'slovacko',
    name: 'FC Slovácko',
    short: 'Slovácko',
    city: 'Uh. Hradiště',
    color: '#C8500A',
    bg: '#fff8f0',
    logo: '/logos/slovacko.png',
    keywords: ['Slovácko', 'FC Slovácko'],
  },
  {
    slug: 'mlada-boleslav',
    name: 'FK Mladá Boleslav',
    short: 'Ml. Boleslav',
    city: 'Ml. Boleslav',
    color: '#005BAC',
    bg: '#f0f6ff',
    logo: '/logos/mlada-boleslav.png',
    keywords: ['Mladá Boleslav', 'Mlada Boleslav', 'FK Boleslav'],
  },
  {
    slug: 'jablonec',
    name: 'FK Jablonec',
    short: 'Jablonec',
    city: 'Jablonec n. N.',
    color: '#F7A600',
    bg: '#fffbf0',
    logo: '/logos/jablonec.png',
    keywords: ['Jablonec', 'FK Jablonec'],
  },
  {
    slug: 'teplice',
    name: 'FK Teplice',
    short: 'Teplice',
    city: 'Teplice',
    color: '#C8A200',
    bg: '#fffdf0',
    logo: '/logos/teplice.png',
    keywords: ['Teplice', 'FK Teplice'],
  },
  {
    slug: 'karvina',
    name: 'MFK Karviná',
    short: 'Karviná',
    city: 'Karviná',
    color: '#00529B',
    bg: '#f0f6ff',
    logo: '/logos/karvina.png',
    keywords: ['Karviná', 'MFK Karviná', 'Karvina'],
  },
  {
    slug: 'hradec-kralove',
    name: 'FC Hradec Králové',
    short: 'Hradec',
    city: 'Hradec Králové',
    color: '#CC0000',
    bg: '#fff0f0',
    logo: '/logos/hradec-kralove.png',
    keywords: ['Hradec Králové', 'FC Hradec', 'Hradec Kralove'],
  },
  {
    slug: 'ceske-budejovice',
    name: 'SK Dynamo Č. Budějovice',
    short: 'Dynamo',
    city: 'Č. Budějovice',
    color: '#1A1A1A',
    bg: '#f5f5f5',
    logo: '/logos/ceske-budejovice.png',
    keywords: ['Dynamo', 'České Budějovice', 'Dynamo Budějovice'],
  },
  {
    slug: 'zbrojovka-brno',
    name: 'FC Zbrojovka Brno',
    short: 'Zbrojovka',
    city: 'Brno',
    color: '#003DA5',
    bg: '#f0f4ff',
    logo: '/logos/zbrojovka-brno.png',
    keywords: ['Zbrojovka', 'Zbrojovka Brno', 'FC Zbrojovka', 'brněnští'],
  },
  {
    slug: 'pardubice',
    name: 'FK Pardubice',
    short: 'Pardubice',
    city: 'Pardubice',
    color: '#002F6C',
    bg: '#E8F0FE',
    logo: '/logos/pardubice.png',
    keywords: ['Pardubice', 'Pardubic', 'Pardubicích', 'Pardubicemi', 'FK Pardubice', 'pardubický'],
  },
  {
    slug: 'zlin',
    name: 'FC Trinity Zlín',
    short: 'Zlín',
    city: 'Zlín',
    color: '#FFD700',
    bg: '#FFFDE7',
    logo: '/logos/zlin.png',
    keywords: ['Zlín', 'Zlína', 'Zlínu', 'Zlínem', 'FC Zlín', 'Trinity Zlín', 'zlínský', 'Fastav'],
  },
  {
    slug: 'dukla-praha',
    name: 'FK Dukla Praha',
    short: 'Dukla',
    city: 'Praha',
    color: '#CC9900',
    bg: '#fffbf0',
    logo: '/logos/dukla-praha.png',
    keywords: ['Dukla', 'Dukla Praha', 'FK Dukla'],
  },
]

export const SOURCES = ['iSport.cz', 'Sport.cz', 'ČT Sport', 'EuroFotbal.cz', 'iDnes.cz']

export const SOURCE_STYLES = {
  'iSport.cz':       { bg: '#FDECEA', color: '#B71C1C' },
  'Sport.cz':        { bg: '#E3F0FF', color: '#0D47A1' },
  'ČT Sport':        { bg: '#E8EAF6', color: '#1A237E' },
  'Slavia Praha':    { bg: '#FDECEA', color: '#CC0000' },
  'Sparta Praha':    { bg: '#FDECEA', color: '#AC1A2F' },
  'Viktoria Plzeň':  { bg: '#E3F0FF', color: '#003087' },
  'Sigma Olomouc':   { bg: '#E3F0FF', color: '#003366' },
  'Bohemians 1905':  { bg: '#E8F5E9', color: '#007A33' },
  'Slovan Liberec':  { bg: '#E3F0FF', color: '#003DA5' },
  'FC Slovácko':     { bg: '#FFF3E0', color: '#C8500A' },
  'Mladá Boleslav':  { bg: '#E3F0FF', color: '#005BAC' },
  'FK Jablonec':     { bg: '#FFF3E0', color: '#F7A600' },
  'FK Teplice':      { bg: '#FFFDE7', color: '#C8A200' },
  'MFK Karviná':     { bg: '#E3F0FF', color: '#00529B' },
  'Hradec Králové':  { bg: '#FDECEA', color: '#CC0000' },
  'Dynamo Č.B.':     { bg: '#F5F5F5', color: '#1A1A1A' },
  'Zbrojovka Brno':  { bg: '#E3F0FF', color: '#003DA5' },
  'Dukla Praha':     { bg: '#FFFDE7', color: '#CC9900' },
  'EuroFotbal.cz':  { bg: '#F3E5F5', color: '#6A1B9A' },
  'iDnes.cz':       { bg: '#FFEBEE', color: '#D32F2F' },
  'Google News':    { bg: '#E8F0FE', color: '#1A73E8' },
}

export function getSourceStyle(name) {
  return SOURCE_STYLES[name] || { bg: '#F3F3F3', color: '#444444' }
}
