// Loga klubů z thesportsdb.com — volně dostupné CDN pro fotbalová loga
export const CLUBS = [
  {
    slug: 'slavia-praha',
    name: 'SK Slavia Praha',
    short: 'Slavia',
    city: 'Praha',
    color: '#CC0000',
    bg: '#fff0f0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/8/82/SK_Slavia_Prague_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/slavia-prague-logo.png',
    keywords: ['Slavia', 'SK Slavia', 'Slavia Praha'],
  },
  {
    slug: 'sparta-praha',
    name: 'AC Sparta Praha',
    short: 'Sparta',
    city: 'Praha',
    color: '#AC1A2F',
    bg: '#fff0f2',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f5/AC_Sparta_Prague_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/sparta-prague-logo.png',
    keywords: ['Sparta', 'AC Sparta', 'Sparta Praha'],
  },
  {
    slug: 'viktoria-plzen',
    name: 'FC Viktoria Plzeň',
    short: 'Plzeň',
    city: 'Plzeň',
    color: '#003087',
    bg: '#f0f4ff',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/37/FC_Viktoria_Plze%C5%88_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/viktoria-plzen.png',
    keywords: ['Plzeň', 'Viktoria Plzeň', 'Viktoria Plzen'],
  },
  {
    slug: 'banik-ostrava',
    name: 'FC Baník Ostrava',
    short: 'Baník',
    city: 'Ostrava',
    color: '#005CA9',
    bg: '#f0f6ff',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b5/FC_Banik_Ostrava_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/banik-ostrava.png',
    keywords: ['Baník', 'Baník Ostrava', 'Banik Ostrava'],
  },
  {
    slug: 'sigma-olomouc',
    name: 'SK Sigma Olomouc',
    short: 'Sigma',
    city: 'Olomouc',
    color: '#003366',
    bg: '#f0f4ff',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e4/SK_Sigma_Olomouc_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/sigma-olomouc.png',
    keywords: ['Sigma', 'Sigma Olomouc', 'SK Sigma'],
  },
  {
    slug: 'bohemians-1905',
    name: 'Bohemians Praha 1905',
    short: 'Bohemians',
    city: 'Praha',
    color: '#007A33',
    bg: '#f0fff4',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/db/Bohemians_1905_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/bohemians-1905.png',
    keywords: ['Bohemians', 'Bohemians 1905', 'Bohemka'],
  },
  {
    slug: 'slovan-liberec',
    name: 'FC Slovan Liberec',
    short: 'Liberec',
    city: 'Liberec',
    color: '#003DA5',
    bg: '#f0f4ff',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/5d/FC_Slovan_Liberec_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/slovan-liberec.png',
    keywords: ['Liberec', 'Slovan Liberec', 'FC Liberec'],
  },
  {
    slug: 'slovacko',
    name: 'FC Slovácko',
    short: 'Slovácko',
    city: 'Uh. Hradiště',
    color: '#C8500A',
    bg: '#fff8f0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c4/FC_Slova%CC%81cko_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/fc-slovacko.png',
    keywords: ['Slovácko', 'FC Slovácko'],
  },
  {
    slug: 'mlada-boleslav',
    name: 'FK Mladá Boleslav',
    short: 'Ml. Boleslav',
    city: 'Ml. Boleslav',
    color: '#005BAC',
    bg: '#f0f6ff',
    logo: 'https://upload.wikimedia.org/wikipedia/en/7/7c/FK_Mlad%C3%A1_Boleslav_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/mlada-boleslav.png',
    keywords: ['Mladá Boleslav', 'Mlada Boleslav', 'FK Boleslav'],
  },
  {
    slug: 'jablonec',
    name: 'FK Jablonec',
    short: 'Jablonec',
    city: 'Jablonec n. N.',
    color: '#F7A600',
    bg: '#fffbf0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/1/16/FK_Jablonec_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/fk-jablonec.png',
    keywords: ['Jablonec', 'FK Jablonec'],
  },
  {
    slug: 'teplice',
    name: 'FK Teplice',
    short: 'Teplice',
    city: 'Teplice',
    color: '#C8A200',
    bg: '#fffdf0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/55/FK_Teplice_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/fk-teplice.png',
    keywords: ['Teplice', 'FK Teplice'],
  },
  {
    slug: 'karvina',
    name: 'MFK Karviná',
    short: 'Karviná',
    city: 'Karviná',
    color: '#00529B',
    bg: '#f0f6ff',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/d6/MFK_Karvin%C3%A1_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/mfk-karvina.png',
    keywords: ['Karviná', 'MFK Karviná', 'Karvina'],
  },
  {
    slug: 'hradec-kralove',
    name: 'FC Hradec Králové',
    short: 'Hradec',
    city: 'Hradec Králové',
    color: '#CC0000',
    bg: '#fff0f0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/8/83/FC_Hradec_Kr%C3%A1lov%C3%A9_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/fc-hradec-kralove.png',
    keywords: ['Hradec Králové', 'FC Hradec', 'Hradec Kralove'],
  },
  {
    slug: 'ceske-budejovice',
    name: 'SK Dynamo Č. Budějovice',
    short: 'Dynamo',
    city: 'Č. Budějovice',
    color: '#1A1A1A',
    bg: '#f5f5f5',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b7/SK_Dynamo_%C4%8C._Bud%C4%9Bjovice_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/sk-dynamo.png',
    keywords: ['Dynamo', 'České Budějovice', 'Dynamo Budějovice'],
  },
  {
    slug: 'zizkov',
    name: 'FK Viktoria Žižkov',
    short: 'Žižkov',
    city: 'Praha',
    color: '#8B0000',
    bg: '#fff0f0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/39/FK_Viktoria_%C5%BDi%C5%BEkov_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/fk-viktoria-zizkov.png',
    keywords: ['Žižkov', 'Viktoria Žižkov', 'Zizkov'],
  },
  {
    slug: 'dukla-praha',
    name: 'FK Dukla Praha',
    short: 'Dukla',
    city: 'Praha',
    color: '#CC9900',
    bg: '#fffbf0',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/34/FK_Dukla_Praha_logo.svg',
    logoPng: 'https://www.thesportsdb.com/images/media/team/badge/fk-dukla-praha.png',
    keywords: ['Dukla', 'Dukla Praha', 'FK Dukla'],
  },
]

export const SOURCES = ['iSport.cz', 'Sport.cz', 'Fotbal.cz', 'ČT Sport', 'Deník.cz', 'inFotbal.cz']

export const SOURCE_STYLES = {
  'iSport.cz':    { bg: '#FDECEA', color: '#B71C1C' },
  'Sport.cz':     { bg: '#E3F0FF', color: '#0D47A1' },
  'Fotbal.cz':    { bg: '#E8F5E9', color: '#1B5E20' },
  'ČT Sport':     { bg: '#E8EAF6', color: '#1A237E' },
  'Deník.cz':     { bg: '#FFF3E0', color: '#E65100' },
  'inFotbal.cz':  { bg: '#E8F5ED', color: '#1A7F3C' },
}
